// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFsvZoSlBmWmH9rpwQe5bfHYGldXEcZDU',
    appId: '1:983951072286:web:ca67e971473b862b79220f',
    messagingSenderId: '983951072286',
    projectId: 'software-ingeconomica',
    authDomain: 'software-ingeconomica.firebaseapp.com',
    storageBucket: 'software-ingeconomica.appspot.com',
    measurementId: 'G-7GV8VFZGT2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUHE6hIq3DkCDaJzbJ4m1D8N00Y7EXhYE',
    appId: '1:983951072286:android:2e514c4244b667f779220f',
    messagingSenderId: '983951072286',
    projectId: 'software-ingeconomica',
    storageBucket: 'software-ingeconomica.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAk5IYxpDIsk0bX5ZnUnbachL7DE57ot70',
    appId: '1:983951072286:ios:f70a13406d263b5979220f',
    messagingSenderId: '983951072286',
    projectId: 'software-ingeconomica',
    storageBucket: 'software-ingeconomica.appspot.com',
    iosBundleId: 'com.example.softwareIngenieriaeconomica',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAk5IYxpDIsk0bX5ZnUnbachL7DE57ot70',
    appId: '1:983951072286:ios:f70a13406d263b5979220f',
    messagingSenderId: '983951072286',
    projectId: 'software-ingeconomica',
    storageBucket: 'software-ingeconomica.appspot.com',
    iosBundleId: 'com.example.softwareIngenieriaeconomica',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFsvZoSlBmWmH9rpwQe5bfHYGldXEcZDU',
    appId: '1:983951072286:web:e325d847c083165a79220f',
    messagingSenderId: '983951072286',
    projectId: 'software-ingeconomica',
    authDomain: 'software-ingeconomica.firebaseapp.com',
    storageBucket: 'software-ingeconomica.appspot.com',
    measurementId: 'G-Q5JZK20NE0',
  );
}
